[package]
name = "gm_reader"
version = "0.1.0"
authors = ["Eli Lipsitz <eli.lipsitz@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
encoding_rs = "0.8.22"
crc = "^1.0.0"
image = "0.23.2"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.14.3"
serde_bytes = "0.11.3"
